name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Required for triggering from API

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    # --- BEGIN GRADLE CACHE SETUP ---
    - name: Setup Gradle Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    # --- END GRADLE CACHE SETUP ---

    - name: Install Android SDK
      run: |
        mkdir -p $ANDROID_HOME/cmdline-tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
        unzip -q cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
        mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
        echo "PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_ENV
      env:
        ANDROID_HOME: /usr/local/lib/android/sdk

    - name: Accept Android SDK licenses
      run: yes | sdkmanager --licenses
      env:
        ANDROID_HOME: /usr/local/lib/android/sdk

    - name: Verify Gradle wrapper exists
      run: |
        ls -l gradlew
        if [ ! -f "./gradlew" ]; then echo "gradlew not found"; exit 1; fi

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build the APK
      run: ./gradlew assembleDebug --stacktrace --info
      env:
        ANDROID_HOME: /usr/local/lib/android/sdk
        ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    - name: Verify APK exists
      run: |
        ls -l app/build/outputs/apk/debug/
        if [ ! -f "app/build/outputs/apk/debug/app-debug.apk" ]; then echo "APK not found"; exit 1; fi

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
